export default defineEventHandler((event) => {
  return {
    clients: [
      {
        id: 1,
        name: "John Doe",
        age: 35,
        email: "john.doe@example.com",
        phone: "(123) 456-7890",
        city: "New York",
      },
      {
        id: 2,
        name: "Jane Smith",
        age: 28,
        email: "jane.smith@example.com",
        phone: "(234) 567-8901",
        city: "Los Angeles",
      },
      {
        id: 3,
        name: "Michael Johnson",
        age: 45,
        email: "michael.johnson@example.com",
        phone: "(345) 678-9012",
        city: "Chicago",
      },
      {
        id: 4,
        name: "Emily Brown",
        age: 32,
        email: "emily.brown@example.com",
        phone: "(456) 789-0123",
        city: "Houston",
      },
      {
        id: 5,
        name: "Daniel Wilson",
        age: 40,
        email: "daniel.wilson@example.com",
        phone: "(567) 890-1234",
        city: "Phoenix",
      },
      {
        id: 6,
        name: "Sarah Taylor",
        age: 29,
        email: "sarah.taylor@example.com",
        phone: "(678) 901-2345",
        city: "Philadelphia",
      },
      {
        id: 7,
        name: "Christopher Martinez",
        age: 38,
        email: "christopher.martinez@example.com",
        phone: "(789) 012-3456",
        city: "San Antonio",
      },
      {
        id: 8,
        name: "Amanda Anderson",
        age: 31,
        email: "amanda.anderson@example.com",
        phone: "(890) 123-4567",
        city: "San Diego",
      },
      {
        id: 9,
        name: "James Thomas",
        age: 36,
        email: "james.thomas@example.com",
        phone: "(901) 234-5678",
        city: "Dallas",
      },
      {
        id: 10,
        name: "Jessica Garcia",
        age: 27,
        email: "jessica.garcia@example.com",
        phone: "(012) 345-6789",
        city: "San Jose",
      },
    ],
  };
});
